// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/merynayr/jwtauth/internal/repository.AuthRepository -o auth_repository_minimock.go -n AuthRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/merynayr/jwtauth/internal/model"
)

// AuthRepositoryMock implements mm_repository.AuthRepository
type AuthRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateRefreshToken          func(ctx context.Context, token *model.RefreshToken) (rp1 *model.RefreshToken, err error)
	funcCreateRefreshTokenOrigin    string
	inspectFuncCreateRefreshToken   func(ctx context.Context, token *model.RefreshToken)
	afterCreateRefreshTokenCounter  uint64
	beforeCreateRefreshTokenCounter uint64
	CreateRefreshTokenMock          mAuthRepositoryMockCreateRefreshToken

	funcDeleteByID          func(ctx context.Context, jti string) (err error)
	funcDeleteByIDOrigin    string
	inspectFuncDeleteByID   func(ctx context.Context, jti string)
	afterDeleteByIDCounter  uint64
	beforeDeleteByIDCounter uint64
	DeleteByIDMock          mAuthRepositoryMockDeleteByID

	funcFindRefreshToken          func(ctx context.Context, jti string) (rp1 *model.RefreshToken, err error)
	funcFindRefreshTokenOrigin    string
	inspectFuncFindRefreshToken   func(ctx context.Context, jti string)
	afterFindRefreshTokenCounter  uint64
	beforeFindRefreshTokenCounter uint64
	FindRefreshTokenMock          mAuthRepositoryMockFindRefreshToken
}

// NewAuthRepositoryMock returns a mock for mm_repository.AuthRepository
func NewAuthRepositoryMock(t minimock.Tester) *AuthRepositoryMock {
	m := &AuthRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateRefreshTokenMock = mAuthRepositoryMockCreateRefreshToken{mock: m}
	m.CreateRefreshTokenMock.callArgs = []*AuthRepositoryMockCreateRefreshTokenParams{}

	m.DeleteByIDMock = mAuthRepositoryMockDeleteByID{mock: m}
	m.DeleteByIDMock.callArgs = []*AuthRepositoryMockDeleteByIDParams{}

	m.FindRefreshTokenMock = mAuthRepositoryMockFindRefreshToken{mock: m}
	m.FindRefreshTokenMock.callArgs = []*AuthRepositoryMockFindRefreshTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthRepositoryMockCreateRefreshToken struct {
	optional           bool
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockCreateRefreshTokenExpectation
	expectations       []*AuthRepositoryMockCreateRefreshTokenExpectation

	callArgs []*AuthRepositoryMockCreateRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthRepositoryMockCreateRefreshTokenExpectation specifies expectation struct of the AuthRepository.CreateRefreshToken
type AuthRepositoryMockCreateRefreshTokenExpectation struct {
	mock               *AuthRepositoryMock
	params             *AuthRepositoryMockCreateRefreshTokenParams
	paramPtrs          *AuthRepositoryMockCreateRefreshTokenParamPtrs
	expectationOrigins AuthRepositoryMockCreateRefreshTokenExpectationOrigins
	results            *AuthRepositoryMockCreateRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// AuthRepositoryMockCreateRefreshTokenParams contains parameters of the AuthRepository.CreateRefreshToken
type AuthRepositoryMockCreateRefreshTokenParams struct {
	ctx   context.Context
	token *model.RefreshToken
}

// AuthRepositoryMockCreateRefreshTokenParamPtrs contains pointers to parameters of the AuthRepository.CreateRefreshToken
type AuthRepositoryMockCreateRefreshTokenParamPtrs struct {
	ctx   *context.Context
	token **model.RefreshToken
}

// AuthRepositoryMockCreateRefreshTokenResults contains results of the AuthRepository.CreateRefreshToken
type AuthRepositoryMockCreateRefreshTokenResults struct {
	rp1 *model.RefreshToken
	err error
}

// AuthRepositoryMockCreateRefreshTokenOrigins contains origins of expectations of the AuthRepository.CreateRefreshToken
type AuthRepositoryMockCreateRefreshTokenExpectationOrigins struct {
	origin      string
	originCtx   string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Optional() *mAuthRepositoryMockCreateRefreshToken {
	mmCreateRefreshToken.optional = true
	return mmCreateRefreshToken
}

// Expect sets up expected params for AuthRepository.CreateRefreshToken
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Expect(ctx context.Context, token *model.RefreshToken) *mAuthRepositoryMockCreateRefreshToken {
	if mmCreateRefreshToken.mock.funcCreateRefreshToken != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Set")
	}

	if mmCreateRefreshToken.defaultExpectation == nil {
		mmCreateRefreshToken.defaultExpectation = &AuthRepositoryMockCreateRefreshTokenExpectation{}
	}

	if mmCreateRefreshToken.defaultExpectation.paramPtrs != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by ExpectParams functions")
	}

	mmCreateRefreshToken.defaultExpectation.params = &AuthRepositoryMockCreateRefreshTokenParams{ctx, token}
	mmCreateRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateRefreshToken.expectations {
		if minimock.Equal(e.params, mmCreateRefreshToken.defaultExpectation.params) {
			mmCreateRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateRefreshToken.defaultExpectation.params)
		}
	}

	return mmCreateRefreshToken
}

// ExpectCtxParam1 sets up expected param ctx for AuthRepository.CreateRefreshToken
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) ExpectCtxParam1(ctx context.Context) *mAuthRepositoryMockCreateRefreshToken {
	if mmCreateRefreshToken.mock.funcCreateRefreshToken != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Set")
	}

	if mmCreateRefreshToken.defaultExpectation == nil {
		mmCreateRefreshToken.defaultExpectation = &AuthRepositoryMockCreateRefreshTokenExpectation{}
	}

	if mmCreateRefreshToken.defaultExpectation.params != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Expect")
	}

	if mmCreateRefreshToken.defaultExpectation.paramPtrs == nil {
		mmCreateRefreshToken.defaultExpectation.paramPtrs = &AuthRepositoryMockCreateRefreshTokenParamPtrs{}
	}
	mmCreateRefreshToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateRefreshToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateRefreshToken
}

// ExpectTokenParam2 sets up expected param token for AuthRepository.CreateRefreshToken
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) ExpectTokenParam2(token *model.RefreshToken) *mAuthRepositoryMockCreateRefreshToken {
	if mmCreateRefreshToken.mock.funcCreateRefreshToken != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Set")
	}

	if mmCreateRefreshToken.defaultExpectation == nil {
		mmCreateRefreshToken.defaultExpectation = &AuthRepositoryMockCreateRefreshTokenExpectation{}
	}

	if mmCreateRefreshToken.defaultExpectation.params != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Expect")
	}

	if mmCreateRefreshToken.defaultExpectation.paramPtrs == nil {
		mmCreateRefreshToken.defaultExpectation.paramPtrs = &AuthRepositoryMockCreateRefreshTokenParamPtrs{}
	}
	mmCreateRefreshToken.defaultExpectation.paramPtrs.token = &token
	mmCreateRefreshToken.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmCreateRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.CreateRefreshToken
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Inspect(f func(ctx context.Context, token *model.RefreshToken)) *mAuthRepositoryMockCreateRefreshToken {
	if mmCreateRefreshToken.mock.inspectFuncCreateRefreshToken != nil {
		mmCreateRefreshToken.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.CreateRefreshToken")
	}

	mmCreateRefreshToken.mock.inspectFuncCreateRefreshToken = f

	return mmCreateRefreshToken
}

// Return sets up results that will be returned by AuthRepository.CreateRefreshToken
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Return(rp1 *model.RefreshToken, err error) *AuthRepositoryMock {
	if mmCreateRefreshToken.mock.funcCreateRefreshToken != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Set")
	}

	if mmCreateRefreshToken.defaultExpectation == nil {
		mmCreateRefreshToken.defaultExpectation = &AuthRepositoryMockCreateRefreshTokenExpectation{mock: mmCreateRefreshToken.mock}
	}
	mmCreateRefreshToken.defaultExpectation.results = &AuthRepositoryMockCreateRefreshTokenResults{rp1, err}
	mmCreateRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateRefreshToken.mock
}

// Set uses given function f to mock the AuthRepository.CreateRefreshToken method
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Set(f func(ctx context.Context, token *model.RefreshToken) (rp1 *model.RefreshToken, err error)) *AuthRepositoryMock {
	if mmCreateRefreshToken.defaultExpectation != nil {
		mmCreateRefreshToken.mock.t.Fatalf("Default expectation is already set for the AuthRepository.CreateRefreshToken method")
	}

	if len(mmCreateRefreshToken.expectations) > 0 {
		mmCreateRefreshToken.mock.t.Fatalf("Some expectations are already set for the AuthRepository.CreateRefreshToken method")
	}

	mmCreateRefreshToken.mock.funcCreateRefreshToken = f
	mmCreateRefreshToken.mock.funcCreateRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmCreateRefreshToken.mock
}

// When sets expectation for the AuthRepository.CreateRefreshToken which will trigger the result defined by the following
// Then helper
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) When(ctx context.Context, token *model.RefreshToken) *AuthRepositoryMockCreateRefreshTokenExpectation {
	if mmCreateRefreshToken.mock.funcCreateRefreshToken != nil {
		mmCreateRefreshToken.mock.t.Fatalf("AuthRepositoryMock.CreateRefreshToken mock is already set by Set")
	}

	expectation := &AuthRepositoryMockCreateRefreshTokenExpectation{
		mock:               mmCreateRefreshToken.mock,
		params:             &AuthRepositoryMockCreateRefreshTokenParams{ctx, token},
		expectationOrigins: AuthRepositoryMockCreateRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateRefreshToken.expectations = append(mmCreateRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.CreateRefreshToken return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockCreateRefreshTokenExpectation) Then(rp1 *model.RefreshToken, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockCreateRefreshTokenResults{rp1, err}
	return e.mock
}

// Times sets number of times AuthRepository.CreateRefreshToken should be invoked
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Times(n uint64) *mAuthRepositoryMockCreateRefreshToken {
	if n == 0 {
		mmCreateRefreshToken.mock.t.Fatalf("Times of AuthRepositoryMock.CreateRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateRefreshToken.expectedInvocations, n)
	mmCreateRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateRefreshToken
}

func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) invocationsDone() bool {
	if len(mmCreateRefreshToken.expectations) == 0 && mmCreateRefreshToken.defaultExpectation == nil && mmCreateRefreshToken.mock.funcCreateRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateRefreshToken.mock.afterCreateRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateRefreshToken implements mm_repository.AuthRepository
func (mmCreateRefreshToken *AuthRepositoryMock) CreateRefreshToken(ctx context.Context, token *model.RefreshToken) (rp1 *model.RefreshToken, err error) {
	mm_atomic.AddUint64(&mmCreateRefreshToken.beforeCreateRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateRefreshToken.afterCreateRefreshTokenCounter, 1)

	mmCreateRefreshToken.t.Helper()

	if mmCreateRefreshToken.inspectFuncCreateRefreshToken != nil {
		mmCreateRefreshToken.inspectFuncCreateRefreshToken(ctx, token)
	}

	mm_params := AuthRepositoryMockCreateRefreshTokenParams{ctx, token}

	// Record call args
	mmCreateRefreshToken.CreateRefreshTokenMock.mutex.Lock()
	mmCreateRefreshToken.CreateRefreshTokenMock.callArgs = append(mmCreateRefreshToken.CreateRefreshTokenMock.callArgs, &mm_params)
	mmCreateRefreshToken.CreateRefreshTokenMock.mutex.Unlock()

	for _, e := range mmCreateRefreshToken.CreateRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := AuthRepositoryMockCreateRefreshTokenParams{ctx, token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateRefreshToken.t.Errorf("AuthRepositoryMock.CreateRefreshToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmCreateRefreshToken.t.Errorf("AuthRepositoryMock.CreateRefreshToken got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateRefreshToken.t.Errorf("AuthRepositoryMock.CreateRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateRefreshToken.CreateRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateRefreshToken.t.Fatal("No results are set for the AuthRepositoryMock.CreateRefreshToken")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmCreateRefreshToken.funcCreateRefreshToken != nil {
		return mmCreateRefreshToken.funcCreateRefreshToken(ctx, token)
	}
	mmCreateRefreshToken.t.Fatalf("Unexpected call to AuthRepositoryMock.CreateRefreshToken. %v %v", ctx, token)
	return
}

// CreateRefreshTokenAfterCounter returns a count of finished AuthRepositoryMock.CreateRefreshToken invocations
func (mmCreateRefreshToken *AuthRepositoryMock) CreateRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateRefreshToken.afterCreateRefreshTokenCounter)
}

// CreateRefreshTokenBeforeCounter returns a count of AuthRepositoryMock.CreateRefreshToken invocations
func (mmCreateRefreshToken *AuthRepositoryMock) CreateRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateRefreshToken.beforeCreateRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.CreateRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateRefreshToken *mAuthRepositoryMockCreateRefreshToken) Calls() []*AuthRepositoryMockCreateRefreshTokenParams {
	mmCreateRefreshToken.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockCreateRefreshTokenParams, len(mmCreateRefreshToken.callArgs))
	copy(argCopy, mmCreateRefreshToken.callArgs)

	mmCreateRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockCreateRefreshTokenDone returns true if the count of the CreateRefreshToken invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockCreateRefreshTokenDone() bool {
	if m.CreateRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateRefreshTokenMock.invocationsDone()
}

// MinimockCreateRefreshTokenInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockCreateRefreshTokenInspect() {
	for _, e := range m.CreateRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.CreateRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterCreateRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateRefreshTokenMock.defaultExpectation != nil && afterCreateRefreshTokenCounter < 1 {
		if m.CreateRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthRepositoryMock.CreateRefreshToken at\n%s", m.CreateRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.CreateRefreshToken at\n%s with params: %#v", m.CreateRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.CreateRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateRefreshToken != nil && afterCreateRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to AuthRepositoryMock.CreateRefreshToken at\n%s", m.funcCreateRefreshTokenOrigin)
	}

	if !m.CreateRefreshTokenMock.invocationsDone() && afterCreateRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthRepositoryMock.CreateRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateRefreshTokenMock.expectedInvocations), m.CreateRefreshTokenMock.expectedInvocationsOrigin, afterCreateRefreshTokenCounter)
	}
}

type mAuthRepositoryMockDeleteByID struct {
	optional           bool
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockDeleteByIDExpectation
	expectations       []*AuthRepositoryMockDeleteByIDExpectation

	callArgs []*AuthRepositoryMockDeleteByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthRepositoryMockDeleteByIDExpectation specifies expectation struct of the AuthRepository.DeleteByID
type AuthRepositoryMockDeleteByIDExpectation struct {
	mock               *AuthRepositoryMock
	params             *AuthRepositoryMockDeleteByIDParams
	paramPtrs          *AuthRepositoryMockDeleteByIDParamPtrs
	expectationOrigins AuthRepositoryMockDeleteByIDExpectationOrigins
	results            *AuthRepositoryMockDeleteByIDResults
	returnOrigin       string
	Counter            uint64
}

// AuthRepositoryMockDeleteByIDParams contains parameters of the AuthRepository.DeleteByID
type AuthRepositoryMockDeleteByIDParams struct {
	ctx context.Context
	jti string
}

// AuthRepositoryMockDeleteByIDParamPtrs contains pointers to parameters of the AuthRepository.DeleteByID
type AuthRepositoryMockDeleteByIDParamPtrs struct {
	ctx *context.Context
	jti *string
}

// AuthRepositoryMockDeleteByIDResults contains results of the AuthRepository.DeleteByID
type AuthRepositoryMockDeleteByIDResults struct {
	err error
}

// AuthRepositoryMockDeleteByIDOrigins contains origins of expectations of the AuthRepository.DeleteByID
type AuthRepositoryMockDeleteByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originJti string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Optional() *mAuthRepositoryMockDeleteByID {
	mmDeleteByID.optional = true
	return mmDeleteByID
}

// Expect sets up expected params for AuthRepository.DeleteByID
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Expect(ctx context.Context, jti string) *mAuthRepositoryMockDeleteByID {
	if mmDeleteByID.mock.funcDeleteByID != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Set")
	}

	if mmDeleteByID.defaultExpectation == nil {
		mmDeleteByID.defaultExpectation = &AuthRepositoryMockDeleteByIDExpectation{}
	}

	if mmDeleteByID.defaultExpectation.paramPtrs != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by ExpectParams functions")
	}

	mmDeleteByID.defaultExpectation.params = &AuthRepositoryMockDeleteByIDParams{ctx, jti}
	mmDeleteByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteByID.expectations {
		if minimock.Equal(e.params, mmDeleteByID.defaultExpectation.params) {
			mmDeleteByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteByID.defaultExpectation.params)
		}
	}

	return mmDeleteByID
}

// ExpectCtxParam1 sets up expected param ctx for AuthRepository.DeleteByID
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) ExpectCtxParam1(ctx context.Context) *mAuthRepositoryMockDeleteByID {
	if mmDeleteByID.mock.funcDeleteByID != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Set")
	}

	if mmDeleteByID.defaultExpectation == nil {
		mmDeleteByID.defaultExpectation = &AuthRepositoryMockDeleteByIDExpectation{}
	}

	if mmDeleteByID.defaultExpectation.params != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Expect")
	}

	if mmDeleteByID.defaultExpectation.paramPtrs == nil {
		mmDeleteByID.defaultExpectation.paramPtrs = &AuthRepositoryMockDeleteByIDParamPtrs{}
	}
	mmDeleteByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteByID
}

// ExpectJtiParam2 sets up expected param jti for AuthRepository.DeleteByID
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) ExpectJtiParam2(jti string) *mAuthRepositoryMockDeleteByID {
	if mmDeleteByID.mock.funcDeleteByID != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Set")
	}

	if mmDeleteByID.defaultExpectation == nil {
		mmDeleteByID.defaultExpectation = &AuthRepositoryMockDeleteByIDExpectation{}
	}

	if mmDeleteByID.defaultExpectation.params != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Expect")
	}

	if mmDeleteByID.defaultExpectation.paramPtrs == nil {
		mmDeleteByID.defaultExpectation.paramPtrs = &AuthRepositoryMockDeleteByIDParamPtrs{}
	}
	mmDeleteByID.defaultExpectation.paramPtrs.jti = &jti
	mmDeleteByID.defaultExpectation.expectationOrigins.originJti = minimock.CallerInfo(1)

	return mmDeleteByID
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.DeleteByID
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Inspect(f func(ctx context.Context, jti string)) *mAuthRepositoryMockDeleteByID {
	if mmDeleteByID.mock.inspectFuncDeleteByID != nil {
		mmDeleteByID.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.DeleteByID")
	}

	mmDeleteByID.mock.inspectFuncDeleteByID = f

	return mmDeleteByID
}

// Return sets up results that will be returned by AuthRepository.DeleteByID
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Return(err error) *AuthRepositoryMock {
	if mmDeleteByID.mock.funcDeleteByID != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Set")
	}

	if mmDeleteByID.defaultExpectation == nil {
		mmDeleteByID.defaultExpectation = &AuthRepositoryMockDeleteByIDExpectation{mock: mmDeleteByID.mock}
	}
	mmDeleteByID.defaultExpectation.results = &AuthRepositoryMockDeleteByIDResults{err}
	mmDeleteByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteByID.mock
}

// Set uses given function f to mock the AuthRepository.DeleteByID method
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Set(f func(ctx context.Context, jti string) (err error)) *AuthRepositoryMock {
	if mmDeleteByID.defaultExpectation != nil {
		mmDeleteByID.mock.t.Fatalf("Default expectation is already set for the AuthRepository.DeleteByID method")
	}

	if len(mmDeleteByID.expectations) > 0 {
		mmDeleteByID.mock.t.Fatalf("Some expectations are already set for the AuthRepository.DeleteByID method")
	}

	mmDeleteByID.mock.funcDeleteByID = f
	mmDeleteByID.mock.funcDeleteByIDOrigin = minimock.CallerInfo(1)
	return mmDeleteByID.mock
}

// When sets expectation for the AuthRepository.DeleteByID which will trigger the result defined by the following
// Then helper
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) When(ctx context.Context, jti string) *AuthRepositoryMockDeleteByIDExpectation {
	if mmDeleteByID.mock.funcDeleteByID != nil {
		mmDeleteByID.mock.t.Fatalf("AuthRepositoryMock.DeleteByID mock is already set by Set")
	}

	expectation := &AuthRepositoryMockDeleteByIDExpectation{
		mock:               mmDeleteByID.mock,
		params:             &AuthRepositoryMockDeleteByIDParams{ctx, jti},
		expectationOrigins: AuthRepositoryMockDeleteByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteByID.expectations = append(mmDeleteByID.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.DeleteByID return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockDeleteByIDExpectation) Then(err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockDeleteByIDResults{err}
	return e.mock
}

// Times sets number of times AuthRepository.DeleteByID should be invoked
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Times(n uint64) *mAuthRepositoryMockDeleteByID {
	if n == 0 {
		mmDeleteByID.mock.t.Fatalf("Times of AuthRepositoryMock.DeleteByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteByID.expectedInvocations, n)
	mmDeleteByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteByID
}

func (mmDeleteByID *mAuthRepositoryMockDeleteByID) invocationsDone() bool {
	if len(mmDeleteByID.expectations) == 0 && mmDeleteByID.defaultExpectation == nil && mmDeleteByID.mock.funcDeleteByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteByID.mock.afterDeleteByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteByID implements mm_repository.AuthRepository
func (mmDeleteByID *AuthRepositoryMock) DeleteByID(ctx context.Context, jti string) (err error) {
	mm_atomic.AddUint64(&mmDeleteByID.beforeDeleteByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteByID.afterDeleteByIDCounter, 1)

	mmDeleteByID.t.Helper()

	if mmDeleteByID.inspectFuncDeleteByID != nil {
		mmDeleteByID.inspectFuncDeleteByID(ctx, jti)
	}

	mm_params := AuthRepositoryMockDeleteByIDParams{ctx, jti}

	// Record call args
	mmDeleteByID.DeleteByIDMock.mutex.Lock()
	mmDeleteByID.DeleteByIDMock.callArgs = append(mmDeleteByID.DeleteByIDMock.callArgs, &mm_params)
	mmDeleteByID.DeleteByIDMock.mutex.Unlock()

	for _, e := range mmDeleteByID.DeleteByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteByID.DeleteByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteByID.DeleteByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteByID.DeleteByIDMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteByID.DeleteByIDMock.defaultExpectation.paramPtrs

		mm_got := AuthRepositoryMockDeleteByIDParams{ctx, jti}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteByID.t.Errorf("AuthRepositoryMock.DeleteByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteByID.DeleteByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.jti != nil && !minimock.Equal(*mm_want_ptrs.jti, mm_got.jti) {
				mmDeleteByID.t.Errorf("AuthRepositoryMock.DeleteByID got unexpected parameter jti, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteByID.DeleteByIDMock.defaultExpectation.expectationOrigins.originJti, *mm_want_ptrs.jti, mm_got.jti, minimock.Diff(*mm_want_ptrs.jti, mm_got.jti))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteByID.t.Errorf("AuthRepositoryMock.DeleteByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteByID.DeleteByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteByID.DeleteByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteByID.t.Fatal("No results are set for the AuthRepositoryMock.DeleteByID")
		}
		return (*mm_results).err
	}
	if mmDeleteByID.funcDeleteByID != nil {
		return mmDeleteByID.funcDeleteByID(ctx, jti)
	}
	mmDeleteByID.t.Fatalf("Unexpected call to AuthRepositoryMock.DeleteByID. %v %v", ctx, jti)
	return
}

// DeleteByIDAfterCounter returns a count of finished AuthRepositoryMock.DeleteByID invocations
func (mmDeleteByID *AuthRepositoryMock) DeleteByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteByID.afterDeleteByIDCounter)
}

// DeleteByIDBeforeCounter returns a count of AuthRepositoryMock.DeleteByID invocations
func (mmDeleteByID *AuthRepositoryMock) DeleteByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteByID.beforeDeleteByIDCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.DeleteByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteByID *mAuthRepositoryMockDeleteByID) Calls() []*AuthRepositoryMockDeleteByIDParams {
	mmDeleteByID.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockDeleteByIDParams, len(mmDeleteByID.callArgs))
	copy(argCopy, mmDeleteByID.callArgs)

	mmDeleteByID.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteByIDDone returns true if the count of the DeleteByID invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockDeleteByIDDone() bool {
	if m.DeleteByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteByIDMock.invocationsDone()
}

// MinimockDeleteByIDInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockDeleteByIDInspect() {
	for _, e := range m.DeleteByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.DeleteByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteByIDCounter := mm_atomic.LoadUint64(&m.afterDeleteByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteByIDMock.defaultExpectation != nil && afterDeleteByIDCounter < 1 {
		if m.DeleteByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthRepositoryMock.DeleteByID at\n%s", m.DeleteByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.DeleteByID at\n%s with params: %#v", m.DeleteByIDMock.defaultExpectation.expectationOrigins.origin, *m.DeleteByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteByID != nil && afterDeleteByIDCounter < 1 {
		m.t.Errorf("Expected call to AuthRepositoryMock.DeleteByID at\n%s", m.funcDeleteByIDOrigin)
	}

	if !m.DeleteByIDMock.invocationsDone() && afterDeleteByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthRepositoryMock.DeleteByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteByIDMock.expectedInvocations), m.DeleteByIDMock.expectedInvocationsOrigin, afterDeleteByIDCounter)
	}
}

type mAuthRepositoryMockFindRefreshToken struct {
	optional           bool
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockFindRefreshTokenExpectation
	expectations       []*AuthRepositoryMockFindRefreshTokenExpectation

	callArgs []*AuthRepositoryMockFindRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthRepositoryMockFindRefreshTokenExpectation specifies expectation struct of the AuthRepository.FindRefreshToken
type AuthRepositoryMockFindRefreshTokenExpectation struct {
	mock               *AuthRepositoryMock
	params             *AuthRepositoryMockFindRefreshTokenParams
	paramPtrs          *AuthRepositoryMockFindRefreshTokenParamPtrs
	expectationOrigins AuthRepositoryMockFindRefreshTokenExpectationOrigins
	results            *AuthRepositoryMockFindRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// AuthRepositoryMockFindRefreshTokenParams contains parameters of the AuthRepository.FindRefreshToken
type AuthRepositoryMockFindRefreshTokenParams struct {
	ctx context.Context
	jti string
}

// AuthRepositoryMockFindRefreshTokenParamPtrs contains pointers to parameters of the AuthRepository.FindRefreshToken
type AuthRepositoryMockFindRefreshTokenParamPtrs struct {
	ctx *context.Context
	jti *string
}

// AuthRepositoryMockFindRefreshTokenResults contains results of the AuthRepository.FindRefreshToken
type AuthRepositoryMockFindRefreshTokenResults struct {
	rp1 *model.RefreshToken
	err error
}

// AuthRepositoryMockFindRefreshTokenOrigins contains origins of expectations of the AuthRepository.FindRefreshToken
type AuthRepositoryMockFindRefreshTokenExpectationOrigins struct {
	origin    string
	originCtx string
	originJti string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Optional() *mAuthRepositoryMockFindRefreshToken {
	mmFindRefreshToken.optional = true
	return mmFindRefreshToken
}

// Expect sets up expected params for AuthRepository.FindRefreshToken
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Expect(ctx context.Context, jti string) *mAuthRepositoryMockFindRefreshToken {
	if mmFindRefreshToken.mock.funcFindRefreshToken != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Set")
	}

	if mmFindRefreshToken.defaultExpectation == nil {
		mmFindRefreshToken.defaultExpectation = &AuthRepositoryMockFindRefreshTokenExpectation{}
	}

	if mmFindRefreshToken.defaultExpectation.paramPtrs != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by ExpectParams functions")
	}

	mmFindRefreshToken.defaultExpectation.params = &AuthRepositoryMockFindRefreshTokenParams{ctx, jti}
	mmFindRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFindRefreshToken.expectations {
		if minimock.Equal(e.params, mmFindRefreshToken.defaultExpectation.params) {
			mmFindRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFindRefreshToken.defaultExpectation.params)
		}
	}

	return mmFindRefreshToken
}

// ExpectCtxParam1 sets up expected param ctx for AuthRepository.FindRefreshToken
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) ExpectCtxParam1(ctx context.Context) *mAuthRepositoryMockFindRefreshToken {
	if mmFindRefreshToken.mock.funcFindRefreshToken != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Set")
	}

	if mmFindRefreshToken.defaultExpectation == nil {
		mmFindRefreshToken.defaultExpectation = &AuthRepositoryMockFindRefreshTokenExpectation{}
	}

	if mmFindRefreshToken.defaultExpectation.params != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Expect")
	}

	if mmFindRefreshToken.defaultExpectation.paramPtrs == nil {
		mmFindRefreshToken.defaultExpectation.paramPtrs = &AuthRepositoryMockFindRefreshTokenParamPtrs{}
	}
	mmFindRefreshToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmFindRefreshToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmFindRefreshToken
}

// ExpectJtiParam2 sets up expected param jti for AuthRepository.FindRefreshToken
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) ExpectJtiParam2(jti string) *mAuthRepositoryMockFindRefreshToken {
	if mmFindRefreshToken.mock.funcFindRefreshToken != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Set")
	}

	if mmFindRefreshToken.defaultExpectation == nil {
		mmFindRefreshToken.defaultExpectation = &AuthRepositoryMockFindRefreshTokenExpectation{}
	}

	if mmFindRefreshToken.defaultExpectation.params != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Expect")
	}

	if mmFindRefreshToken.defaultExpectation.paramPtrs == nil {
		mmFindRefreshToken.defaultExpectation.paramPtrs = &AuthRepositoryMockFindRefreshTokenParamPtrs{}
	}
	mmFindRefreshToken.defaultExpectation.paramPtrs.jti = &jti
	mmFindRefreshToken.defaultExpectation.expectationOrigins.originJti = minimock.CallerInfo(1)

	return mmFindRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.FindRefreshToken
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Inspect(f func(ctx context.Context, jti string)) *mAuthRepositoryMockFindRefreshToken {
	if mmFindRefreshToken.mock.inspectFuncFindRefreshToken != nil {
		mmFindRefreshToken.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.FindRefreshToken")
	}

	mmFindRefreshToken.mock.inspectFuncFindRefreshToken = f

	return mmFindRefreshToken
}

// Return sets up results that will be returned by AuthRepository.FindRefreshToken
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Return(rp1 *model.RefreshToken, err error) *AuthRepositoryMock {
	if mmFindRefreshToken.mock.funcFindRefreshToken != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Set")
	}

	if mmFindRefreshToken.defaultExpectation == nil {
		mmFindRefreshToken.defaultExpectation = &AuthRepositoryMockFindRefreshTokenExpectation{mock: mmFindRefreshToken.mock}
	}
	mmFindRefreshToken.defaultExpectation.results = &AuthRepositoryMockFindRefreshTokenResults{rp1, err}
	mmFindRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFindRefreshToken.mock
}

// Set uses given function f to mock the AuthRepository.FindRefreshToken method
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Set(f func(ctx context.Context, jti string) (rp1 *model.RefreshToken, err error)) *AuthRepositoryMock {
	if mmFindRefreshToken.defaultExpectation != nil {
		mmFindRefreshToken.mock.t.Fatalf("Default expectation is already set for the AuthRepository.FindRefreshToken method")
	}

	if len(mmFindRefreshToken.expectations) > 0 {
		mmFindRefreshToken.mock.t.Fatalf("Some expectations are already set for the AuthRepository.FindRefreshToken method")
	}

	mmFindRefreshToken.mock.funcFindRefreshToken = f
	mmFindRefreshToken.mock.funcFindRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmFindRefreshToken.mock
}

// When sets expectation for the AuthRepository.FindRefreshToken which will trigger the result defined by the following
// Then helper
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) When(ctx context.Context, jti string) *AuthRepositoryMockFindRefreshTokenExpectation {
	if mmFindRefreshToken.mock.funcFindRefreshToken != nil {
		mmFindRefreshToken.mock.t.Fatalf("AuthRepositoryMock.FindRefreshToken mock is already set by Set")
	}

	expectation := &AuthRepositoryMockFindRefreshTokenExpectation{
		mock:               mmFindRefreshToken.mock,
		params:             &AuthRepositoryMockFindRefreshTokenParams{ctx, jti},
		expectationOrigins: AuthRepositoryMockFindRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFindRefreshToken.expectations = append(mmFindRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.FindRefreshToken return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockFindRefreshTokenExpectation) Then(rp1 *model.RefreshToken, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockFindRefreshTokenResults{rp1, err}
	return e.mock
}

// Times sets number of times AuthRepository.FindRefreshToken should be invoked
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Times(n uint64) *mAuthRepositoryMockFindRefreshToken {
	if n == 0 {
		mmFindRefreshToken.mock.t.Fatalf("Times of AuthRepositoryMock.FindRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFindRefreshToken.expectedInvocations, n)
	mmFindRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFindRefreshToken
}

func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) invocationsDone() bool {
	if len(mmFindRefreshToken.expectations) == 0 && mmFindRefreshToken.defaultExpectation == nil && mmFindRefreshToken.mock.funcFindRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFindRefreshToken.mock.afterFindRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFindRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// FindRefreshToken implements mm_repository.AuthRepository
func (mmFindRefreshToken *AuthRepositoryMock) FindRefreshToken(ctx context.Context, jti string) (rp1 *model.RefreshToken, err error) {
	mm_atomic.AddUint64(&mmFindRefreshToken.beforeFindRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmFindRefreshToken.afterFindRefreshTokenCounter, 1)

	mmFindRefreshToken.t.Helper()

	if mmFindRefreshToken.inspectFuncFindRefreshToken != nil {
		mmFindRefreshToken.inspectFuncFindRefreshToken(ctx, jti)
	}

	mm_params := AuthRepositoryMockFindRefreshTokenParams{ctx, jti}

	// Record call args
	mmFindRefreshToken.FindRefreshTokenMock.mutex.Lock()
	mmFindRefreshToken.FindRefreshTokenMock.callArgs = append(mmFindRefreshToken.FindRefreshTokenMock.callArgs, &mm_params)
	mmFindRefreshToken.FindRefreshTokenMock.mutex.Unlock()

	for _, e := range mmFindRefreshToken.FindRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := AuthRepositoryMockFindRefreshTokenParams{ctx, jti}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmFindRefreshToken.t.Errorf("AuthRepositoryMock.FindRefreshToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.jti != nil && !minimock.Equal(*mm_want_ptrs.jti, mm_got.jti) {
				mmFindRefreshToken.t.Errorf("AuthRepositoryMock.FindRefreshToken got unexpected parameter jti, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.expectationOrigins.originJti, *mm_want_ptrs.jti, mm_got.jti, minimock.Diff(*mm_want_ptrs.jti, mm_got.jti))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFindRefreshToken.t.Errorf("AuthRepositoryMock.FindRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFindRefreshToken.FindRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmFindRefreshToken.t.Fatal("No results are set for the AuthRepositoryMock.FindRefreshToken")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmFindRefreshToken.funcFindRefreshToken != nil {
		return mmFindRefreshToken.funcFindRefreshToken(ctx, jti)
	}
	mmFindRefreshToken.t.Fatalf("Unexpected call to AuthRepositoryMock.FindRefreshToken. %v %v", ctx, jti)
	return
}

// FindRefreshTokenAfterCounter returns a count of finished AuthRepositoryMock.FindRefreshToken invocations
func (mmFindRefreshToken *AuthRepositoryMock) FindRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFindRefreshToken.afterFindRefreshTokenCounter)
}

// FindRefreshTokenBeforeCounter returns a count of AuthRepositoryMock.FindRefreshToken invocations
func (mmFindRefreshToken *AuthRepositoryMock) FindRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFindRefreshToken.beforeFindRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.FindRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFindRefreshToken *mAuthRepositoryMockFindRefreshToken) Calls() []*AuthRepositoryMockFindRefreshTokenParams {
	mmFindRefreshToken.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockFindRefreshTokenParams, len(mmFindRefreshToken.callArgs))
	copy(argCopy, mmFindRefreshToken.callArgs)

	mmFindRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockFindRefreshTokenDone returns true if the count of the FindRefreshToken invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockFindRefreshTokenDone() bool {
	if m.FindRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FindRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FindRefreshTokenMock.invocationsDone()
}

// MinimockFindRefreshTokenInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockFindRefreshTokenInspect() {
	for _, e := range m.FindRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.FindRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFindRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterFindRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FindRefreshTokenMock.defaultExpectation != nil && afterFindRefreshTokenCounter < 1 {
		if m.FindRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthRepositoryMock.FindRefreshToken at\n%s", m.FindRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.FindRefreshToken at\n%s with params: %#v", m.FindRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.FindRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFindRefreshToken != nil && afterFindRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to AuthRepositoryMock.FindRefreshToken at\n%s", m.funcFindRefreshTokenOrigin)
	}

	if !m.FindRefreshTokenMock.invocationsDone() && afterFindRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthRepositoryMock.FindRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FindRefreshTokenMock.expectedInvocations), m.FindRefreshTokenMock.expectedInvocationsOrigin, afterFindRefreshTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateRefreshTokenInspect()

			m.MinimockDeleteByIDInspect()

			m.MinimockFindRefreshTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateRefreshTokenDone() &&
		m.MinimockDeleteByIDDone() &&
		m.MinimockFindRefreshTokenDone()
}
