// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/merynayr/jwtauth/internal/service.AuthService -o auth_service_minimock.go -n AuthServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/merynayr/jwtauth/internal/model"
)

// AuthServiceMock implements mm_service.AuthService
type AuthServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcIssueTokens          func(ctx context.Context, req model.AuthRequest) (ap1 *model.AuthResponse, err error)
	funcIssueTokensOrigin    string
	inspectFuncIssueTokens   func(ctx context.Context, req model.AuthRequest)
	afterIssueTokensCounter  uint64
	beforeIssueTokensCounter uint64
	IssueTokensMock          mAuthServiceMockIssueTokens

	funcRefreshTokens          func(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string) (ap1 *model.AuthResponse, err error)
	funcRefreshTokensOrigin    string
	inspectFuncRefreshTokens   func(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string)
	afterRefreshTokensCounter  uint64
	beforeRefreshTokensCounter uint64
	RefreshTokensMock          mAuthServiceMockRefreshTokens
}

// NewAuthServiceMock returns a mock for mm_service.AuthService
func NewAuthServiceMock(t minimock.Tester) *AuthServiceMock {
	m := &AuthServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.IssueTokensMock = mAuthServiceMockIssueTokens{mock: m}
	m.IssueTokensMock.callArgs = []*AuthServiceMockIssueTokensParams{}

	m.RefreshTokensMock = mAuthServiceMockRefreshTokens{mock: m}
	m.RefreshTokensMock.callArgs = []*AuthServiceMockRefreshTokensParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthServiceMockIssueTokens struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockIssueTokensExpectation
	expectations       []*AuthServiceMockIssueTokensExpectation

	callArgs []*AuthServiceMockIssueTokensParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockIssueTokensExpectation specifies expectation struct of the AuthService.IssueTokens
type AuthServiceMockIssueTokensExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockIssueTokensParams
	paramPtrs          *AuthServiceMockIssueTokensParamPtrs
	expectationOrigins AuthServiceMockIssueTokensExpectationOrigins
	results            *AuthServiceMockIssueTokensResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockIssueTokensParams contains parameters of the AuthService.IssueTokens
type AuthServiceMockIssueTokensParams struct {
	ctx context.Context
	req model.AuthRequest
}

// AuthServiceMockIssueTokensParamPtrs contains pointers to parameters of the AuthService.IssueTokens
type AuthServiceMockIssueTokensParamPtrs struct {
	ctx *context.Context
	req *model.AuthRequest
}

// AuthServiceMockIssueTokensResults contains results of the AuthService.IssueTokens
type AuthServiceMockIssueTokensResults struct {
	ap1 *model.AuthResponse
	err error
}

// AuthServiceMockIssueTokensOrigins contains origins of expectations of the AuthService.IssueTokens
type AuthServiceMockIssueTokensExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIssueTokens *mAuthServiceMockIssueTokens) Optional() *mAuthServiceMockIssueTokens {
	mmIssueTokens.optional = true
	return mmIssueTokens
}

// Expect sets up expected params for AuthService.IssueTokens
func (mmIssueTokens *mAuthServiceMockIssueTokens) Expect(ctx context.Context, req model.AuthRequest) *mAuthServiceMockIssueTokens {
	if mmIssueTokens.mock.funcIssueTokens != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Set")
	}

	if mmIssueTokens.defaultExpectation == nil {
		mmIssueTokens.defaultExpectation = &AuthServiceMockIssueTokensExpectation{}
	}

	if mmIssueTokens.defaultExpectation.paramPtrs != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by ExpectParams functions")
	}

	mmIssueTokens.defaultExpectation.params = &AuthServiceMockIssueTokensParams{ctx, req}
	mmIssueTokens.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmIssueTokens.expectations {
		if minimock.Equal(e.params, mmIssueTokens.defaultExpectation.params) {
			mmIssueTokens.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIssueTokens.defaultExpectation.params)
		}
	}

	return mmIssueTokens
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.IssueTokens
func (mmIssueTokens *mAuthServiceMockIssueTokens) ExpectCtxParam1(ctx context.Context) *mAuthServiceMockIssueTokens {
	if mmIssueTokens.mock.funcIssueTokens != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Set")
	}

	if mmIssueTokens.defaultExpectation == nil {
		mmIssueTokens.defaultExpectation = &AuthServiceMockIssueTokensExpectation{}
	}

	if mmIssueTokens.defaultExpectation.params != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Expect")
	}

	if mmIssueTokens.defaultExpectation.paramPtrs == nil {
		mmIssueTokens.defaultExpectation.paramPtrs = &AuthServiceMockIssueTokensParamPtrs{}
	}
	mmIssueTokens.defaultExpectation.paramPtrs.ctx = &ctx
	mmIssueTokens.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmIssueTokens
}

// ExpectReqParam2 sets up expected param req for AuthService.IssueTokens
func (mmIssueTokens *mAuthServiceMockIssueTokens) ExpectReqParam2(req model.AuthRequest) *mAuthServiceMockIssueTokens {
	if mmIssueTokens.mock.funcIssueTokens != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Set")
	}

	if mmIssueTokens.defaultExpectation == nil {
		mmIssueTokens.defaultExpectation = &AuthServiceMockIssueTokensExpectation{}
	}

	if mmIssueTokens.defaultExpectation.params != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Expect")
	}

	if mmIssueTokens.defaultExpectation.paramPtrs == nil {
		mmIssueTokens.defaultExpectation.paramPtrs = &AuthServiceMockIssueTokensParamPtrs{}
	}
	mmIssueTokens.defaultExpectation.paramPtrs.req = &req
	mmIssueTokens.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmIssueTokens
}

// Inspect accepts an inspector function that has same arguments as the AuthService.IssueTokens
func (mmIssueTokens *mAuthServiceMockIssueTokens) Inspect(f func(ctx context.Context, req model.AuthRequest)) *mAuthServiceMockIssueTokens {
	if mmIssueTokens.mock.inspectFuncIssueTokens != nil {
		mmIssueTokens.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.IssueTokens")
	}

	mmIssueTokens.mock.inspectFuncIssueTokens = f

	return mmIssueTokens
}

// Return sets up results that will be returned by AuthService.IssueTokens
func (mmIssueTokens *mAuthServiceMockIssueTokens) Return(ap1 *model.AuthResponse, err error) *AuthServiceMock {
	if mmIssueTokens.mock.funcIssueTokens != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Set")
	}

	if mmIssueTokens.defaultExpectation == nil {
		mmIssueTokens.defaultExpectation = &AuthServiceMockIssueTokensExpectation{mock: mmIssueTokens.mock}
	}
	mmIssueTokens.defaultExpectation.results = &AuthServiceMockIssueTokensResults{ap1, err}
	mmIssueTokens.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIssueTokens.mock
}

// Set uses given function f to mock the AuthService.IssueTokens method
func (mmIssueTokens *mAuthServiceMockIssueTokens) Set(f func(ctx context.Context, req model.AuthRequest) (ap1 *model.AuthResponse, err error)) *AuthServiceMock {
	if mmIssueTokens.defaultExpectation != nil {
		mmIssueTokens.mock.t.Fatalf("Default expectation is already set for the AuthService.IssueTokens method")
	}

	if len(mmIssueTokens.expectations) > 0 {
		mmIssueTokens.mock.t.Fatalf("Some expectations are already set for the AuthService.IssueTokens method")
	}

	mmIssueTokens.mock.funcIssueTokens = f
	mmIssueTokens.mock.funcIssueTokensOrigin = minimock.CallerInfo(1)
	return mmIssueTokens.mock
}

// When sets expectation for the AuthService.IssueTokens which will trigger the result defined by the following
// Then helper
func (mmIssueTokens *mAuthServiceMockIssueTokens) When(ctx context.Context, req model.AuthRequest) *AuthServiceMockIssueTokensExpectation {
	if mmIssueTokens.mock.funcIssueTokens != nil {
		mmIssueTokens.mock.t.Fatalf("AuthServiceMock.IssueTokens mock is already set by Set")
	}

	expectation := &AuthServiceMockIssueTokensExpectation{
		mock:               mmIssueTokens.mock,
		params:             &AuthServiceMockIssueTokensParams{ctx, req},
		expectationOrigins: AuthServiceMockIssueTokensExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmIssueTokens.expectations = append(mmIssueTokens.expectations, expectation)
	return expectation
}

// Then sets up AuthService.IssueTokens return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockIssueTokensExpectation) Then(ap1 *model.AuthResponse, err error) *AuthServiceMock {
	e.results = &AuthServiceMockIssueTokensResults{ap1, err}
	return e.mock
}

// Times sets number of times AuthService.IssueTokens should be invoked
func (mmIssueTokens *mAuthServiceMockIssueTokens) Times(n uint64) *mAuthServiceMockIssueTokens {
	if n == 0 {
		mmIssueTokens.mock.t.Fatalf("Times of AuthServiceMock.IssueTokens mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIssueTokens.expectedInvocations, n)
	mmIssueTokens.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIssueTokens
}

func (mmIssueTokens *mAuthServiceMockIssueTokens) invocationsDone() bool {
	if len(mmIssueTokens.expectations) == 0 && mmIssueTokens.defaultExpectation == nil && mmIssueTokens.mock.funcIssueTokens == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIssueTokens.mock.afterIssueTokensCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIssueTokens.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// IssueTokens implements mm_service.AuthService
func (mmIssueTokens *AuthServiceMock) IssueTokens(ctx context.Context, req model.AuthRequest) (ap1 *model.AuthResponse, err error) {
	mm_atomic.AddUint64(&mmIssueTokens.beforeIssueTokensCounter, 1)
	defer mm_atomic.AddUint64(&mmIssueTokens.afterIssueTokensCounter, 1)

	mmIssueTokens.t.Helper()

	if mmIssueTokens.inspectFuncIssueTokens != nil {
		mmIssueTokens.inspectFuncIssueTokens(ctx, req)
	}

	mm_params := AuthServiceMockIssueTokensParams{ctx, req}

	// Record call args
	mmIssueTokens.IssueTokensMock.mutex.Lock()
	mmIssueTokens.IssueTokensMock.callArgs = append(mmIssueTokens.IssueTokensMock.callArgs, &mm_params)
	mmIssueTokens.IssueTokensMock.mutex.Unlock()

	for _, e := range mmIssueTokens.IssueTokensMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ap1, e.results.err
		}
	}

	if mmIssueTokens.IssueTokensMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIssueTokens.IssueTokensMock.defaultExpectation.Counter, 1)
		mm_want := mmIssueTokens.IssueTokensMock.defaultExpectation.params
		mm_want_ptrs := mmIssueTokens.IssueTokensMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockIssueTokensParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmIssueTokens.t.Errorf("AuthServiceMock.IssueTokens got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIssueTokens.IssueTokensMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmIssueTokens.t.Errorf("AuthServiceMock.IssueTokens got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIssueTokens.IssueTokensMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIssueTokens.t.Errorf("AuthServiceMock.IssueTokens got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmIssueTokens.IssueTokensMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIssueTokens.IssueTokensMock.defaultExpectation.results
		if mm_results == nil {
			mmIssueTokens.t.Fatal("No results are set for the AuthServiceMock.IssueTokens")
		}
		return (*mm_results).ap1, (*mm_results).err
	}
	if mmIssueTokens.funcIssueTokens != nil {
		return mmIssueTokens.funcIssueTokens(ctx, req)
	}
	mmIssueTokens.t.Fatalf("Unexpected call to AuthServiceMock.IssueTokens. %v %v", ctx, req)
	return
}

// IssueTokensAfterCounter returns a count of finished AuthServiceMock.IssueTokens invocations
func (mmIssueTokens *AuthServiceMock) IssueTokensAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIssueTokens.afterIssueTokensCounter)
}

// IssueTokensBeforeCounter returns a count of AuthServiceMock.IssueTokens invocations
func (mmIssueTokens *AuthServiceMock) IssueTokensBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIssueTokens.beforeIssueTokensCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.IssueTokens.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIssueTokens *mAuthServiceMockIssueTokens) Calls() []*AuthServiceMockIssueTokensParams {
	mmIssueTokens.mutex.RLock()

	argCopy := make([]*AuthServiceMockIssueTokensParams, len(mmIssueTokens.callArgs))
	copy(argCopy, mmIssueTokens.callArgs)

	mmIssueTokens.mutex.RUnlock()

	return argCopy
}

// MinimockIssueTokensDone returns true if the count of the IssueTokens invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockIssueTokensDone() bool {
	if m.IssueTokensMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IssueTokensMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IssueTokensMock.invocationsDone()
}

// MinimockIssueTokensInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockIssueTokensInspect() {
	for _, e := range m.IssueTokensMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.IssueTokens at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterIssueTokensCounter := mm_atomic.LoadUint64(&m.afterIssueTokensCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IssueTokensMock.defaultExpectation != nil && afterIssueTokensCounter < 1 {
		if m.IssueTokensMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.IssueTokens at\n%s", m.IssueTokensMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.IssueTokens at\n%s with params: %#v", m.IssueTokensMock.defaultExpectation.expectationOrigins.origin, *m.IssueTokensMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIssueTokens != nil && afterIssueTokensCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.IssueTokens at\n%s", m.funcIssueTokensOrigin)
	}

	if !m.IssueTokensMock.invocationsDone() && afterIssueTokensCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.IssueTokens at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IssueTokensMock.expectedInvocations), m.IssueTokensMock.expectedInvocationsOrigin, afterIssueTokensCounter)
	}
}

type mAuthServiceMockRefreshTokens struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockRefreshTokensExpectation
	expectations       []*AuthServiceMockRefreshTokensExpectation

	callArgs []*AuthServiceMockRefreshTokensParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockRefreshTokensExpectation specifies expectation struct of the AuthService.RefreshTokens
type AuthServiceMockRefreshTokensExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockRefreshTokensParams
	paramPtrs          *AuthServiceMockRefreshTokensParamPtrs
	expectationOrigins AuthServiceMockRefreshTokensExpectationOrigins
	results            *AuthServiceMockRefreshTokensResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockRefreshTokensParams contains parameters of the AuthService.RefreshTokens
type AuthServiceMockRefreshTokensParams struct {
	ctx             context.Context
	refreshTokenRaw string
	accessTokenRaw  string
	ip              string
	userAgent       string
}

// AuthServiceMockRefreshTokensParamPtrs contains pointers to parameters of the AuthService.RefreshTokens
type AuthServiceMockRefreshTokensParamPtrs struct {
	ctx             *context.Context
	refreshTokenRaw *string
	accessTokenRaw  *string
	ip              *string
	userAgent       *string
}

// AuthServiceMockRefreshTokensResults contains results of the AuthService.RefreshTokens
type AuthServiceMockRefreshTokensResults struct {
	ap1 *model.AuthResponse
	err error
}

// AuthServiceMockRefreshTokensOrigins contains origins of expectations of the AuthService.RefreshTokens
type AuthServiceMockRefreshTokensExpectationOrigins struct {
	origin                string
	originCtx             string
	originRefreshTokenRaw string
	originAccessTokenRaw  string
	originIp              string
	originUserAgent       string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Optional() *mAuthServiceMockRefreshTokens {
	mmRefreshTokens.optional = true
	return mmRefreshTokens
}

// Expect sets up expected params for AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Expect(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{}
	}

	if mmRefreshTokens.defaultExpectation.paramPtrs != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by ExpectParams functions")
	}

	mmRefreshTokens.defaultExpectation.params = &AuthServiceMockRefreshTokensParams{ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent}
	mmRefreshTokens.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRefreshTokens.expectations {
		if minimock.Equal(e.params, mmRefreshTokens.defaultExpectation.params) {
			mmRefreshTokens.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRefreshTokens.defaultExpectation.params)
		}
	}

	return mmRefreshTokens
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) ExpectCtxParam1(ctx context.Context) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{}
	}

	if mmRefreshTokens.defaultExpectation.params != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Expect")
	}

	if mmRefreshTokens.defaultExpectation.paramPtrs == nil {
		mmRefreshTokens.defaultExpectation.paramPtrs = &AuthServiceMockRefreshTokensParamPtrs{}
	}
	mmRefreshTokens.defaultExpectation.paramPtrs.ctx = &ctx
	mmRefreshTokens.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRefreshTokens
}

// ExpectRefreshTokenRawParam2 sets up expected param refreshTokenRaw for AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) ExpectRefreshTokenRawParam2(refreshTokenRaw string) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{}
	}

	if mmRefreshTokens.defaultExpectation.params != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Expect")
	}

	if mmRefreshTokens.defaultExpectation.paramPtrs == nil {
		mmRefreshTokens.defaultExpectation.paramPtrs = &AuthServiceMockRefreshTokensParamPtrs{}
	}
	mmRefreshTokens.defaultExpectation.paramPtrs.refreshTokenRaw = &refreshTokenRaw
	mmRefreshTokens.defaultExpectation.expectationOrigins.originRefreshTokenRaw = minimock.CallerInfo(1)

	return mmRefreshTokens
}

// ExpectAccessTokenRawParam3 sets up expected param accessTokenRaw for AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) ExpectAccessTokenRawParam3(accessTokenRaw string) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{}
	}

	if mmRefreshTokens.defaultExpectation.params != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Expect")
	}

	if mmRefreshTokens.defaultExpectation.paramPtrs == nil {
		mmRefreshTokens.defaultExpectation.paramPtrs = &AuthServiceMockRefreshTokensParamPtrs{}
	}
	mmRefreshTokens.defaultExpectation.paramPtrs.accessTokenRaw = &accessTokenRaw
	mmRefreshTokens.defaultExpectation.expectationOrigins.originAccessTokenRaw = minimock.CallerInfo(1)

	return mmRefreshTokens
}

// ExpectIpParam4 sets up expected param ip for AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) ExpectIpParam4(ip string) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{}
	}

	if mmRefreshTokens.defaultExpectation.params != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Expect")
	}

	if mmRefreshTokens.defaultExpectation.paramPtrs == nil {
		mmRefreshTokens.defaultExpectation.paramPtrs = &AuthServiceMockRefreshTokensParamPtrs{}
	}
	mmRefreshTokens.defaultExpectation.paramPtrs.ip = &ip
	mmRefreshTokens.defaultExpectation.expectationOrigins.originIp = minimock.CallerInfo(1)

	return mmRefreshTokens
}

// ExpectUserAgentParam5 sets up expected param userAgent for AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) ExpectUserAgentParam5(userAgent string) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{}
	}

	if mmRefreshTokens.defaultExpectation.params != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Expect")
	}

	if mmRefreshTokens.defaultExpectation.paramPtrs == nil {
		mmRefreshTokens.defaultExpectation.paramPtrs = &AuthServiceMockRefreshTokensParamPtrs{}
	}
	mmRefreshTokens.defaultExpectation.paramPtrs.userAgent = &userAgent
	mmRefreshTokens.defaultExpectation.expectationOrigins.originUserAgent = minimock.CallerInfo(1)

	return mmRefreshTokens
}

// Inspect accepts an inspector function that has same arguments as the AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Inspect(f func(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string)) *mAuthServiceMockRefreshTokens {
	if mmRefreshTokens.mock.inspectFuncRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.RefreshTokens")
	}

	mmRefreshTokens.mock.inspectFuncRefreshTokens = f

	return mmRefreshTokens
}

// Return sets up results that will be returned by AuthService.RefreshTokens
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Return(ap1 *model.AuthResponse, err error) *AuthServiceMock {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	if mmRefreshTokens.defaultExpectation == nil {
		mmRefreshTokens.defaultExpectation = &AuthServiceMockRefreshTokensExpectation{mock: mmRefreshTokens.mock}
	}
	mmRefreshTokens.defaultExpectation.results = &AuthServiceMockRefreshTokensResults{ap1, err}
	mmRefreshTokens.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRefreshTokens.mock
}

// Set uses given function f to mock the AuthService.RefreshTokens method
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Set(f func(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string) (ap1 *model.AuthResponse, err error)) *AuthServiceMock {
	if mmRefreshTokens.defaultExpectation != nil {
		mmRefreshTokens.mock.t.Fatalf("Default expectation is already set for the AuthService.RefreshTokens method")
	}

	if len(mmRefreshTokens.expectations) > 0 {
		mmRefreshTokens.mock.t.Fatalf("Some expectations are already set for the AuthService.RefreshTokens method")
	}

	mmRefreshTokens.mock.funcRefreshTokens = f
	mmRefreshTokens.mock.funcRefreshTokensOrigin = minimock.CallerInfo(1)
	return mmRefreshTokens.mock
}

// When sets expectation for the AuthService.RefreshTokens which will trigger the result defined by the following
// Then helper
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) When(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string) *AuthServiceMockRefreshTokensExpectation {
	if mmRefreshTokens.mock.funcRefreshTokens != nil {
		mmRefreshTokens.mock.t.Fatalf("AuthServiceMock.RefreshTokens mock is already set by Set")
	}

	expectation := &AuthServiceMockRefreshTokensExpectation{
		mock:               mmRefreshTokens.mock,
		params:             &AuthServiceMockRefreshTokensParams{ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent},
		expectationOrigins: AuthServiceMockRefreshTokensExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRefreshTokens.expectations = append(mmRefreshTokens.expectations, expectation)
	return expectation
}

// Then sets up AuthService.RefreshTokens return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockRefreshTokensExpectation) Then(ap1 *model.AuthResponse, err error) *AuthServiceMock {
	e.results = &AuthServiceMockRefreshTokensResults{ap1, err}
	return e.mock
}

// Times sets number of times AuthService.RefreshTokens should be invoked
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Times(n uint64) *mAuthServiceMockRefreshTokens {
	if n == 0 {
		mmRefreshTokens.mock.t.Fatalf("Times of AuthServiceMock.RefreshTokens mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRefreshTokens.expectedInvocations, n)
	mmRefreshTokens.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRefreshTokens
}

func (mmRefreshTokens *mAuthServiceMockRefreshTokens) invocationsDone() bool {
	if len(mmRefreshTokens.expectations) == 0 && mmRefreshTokens.defaultExpectation == nil && mmRefreshTokens.mock.funcRefreshTokens == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRefreshTokens.mock.afterRefreshTokensCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRefreshTokens.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RefreshTokens implements mm_service.AuthService
func (mmRefreshTokens *AuthServiceMock) RefreshTokens(ctx context.Context, refreshTokenRaw string, accessTokenRaw string, ip string, userAgent string) (ap1 *model.AuthResponse, err error) {
	mm_atomic.AddUint64(&mmRefreshTokens.beforeRefreshTokensCounter, 1)
	defer mm_atomic.AddUint64(&mmRefreshTokens.afterRefreshTokensCounter, 1)

	mmRefreshTokens.t.Helper()

	if mmRefreshTokens.inspectFuncRefreshTokens != nil {
		mmRefreshTokens.inspectFuncRefreshTokens(ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent)
	}

	mm_params := AuthServiceMockRefreshTokensParams{ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent}

	// Record call args
	mmRefreshTokens.RefreshTokensMock.mutex.Lock()
	mmRefreshTokens.RefreshTokensMock.callArgs = append(mmRefreshTokens.RefreshTokensMock.callArgs, &mm_params)
	mmRefreshTokens.RefreshTokensMock.mutex.Unlock()

	for _, e := range mmRefreshTokens.RefreshTokensMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ap1, e.results.err
		}
	}

	if mmRefreshTokens.RefreshTokensMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRefreshTokens.RefreshTokensMock.defaultExpectation.Counter, 1)
		mm_want := mmRefreshTokens.RefreshTokensMock.defaultExpectation.params
		mm_want_ptrs := mmRefreshTokens.RefreshTokensMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockRefreshTokensParams{ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRefreshTokens.t.Errorf("AuthServiceMock.RefreshTokens got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefreshTokens.RefreshTokensMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.refreshTokenRaw != nil && !minimock.Equal(*mm_want_ptrs.refreshTokenRaw, mm_got.refreshTokenRaw) {
				mmRefreshTokens.t.Errorf("AuthServiceMock.RefreshTokens got unexpected parameter refreshTokenRaw, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefreshTokens.RefreshTokensMock.defaultExpectation.expectationOrigins.originRefreshTokenRaw, *mm_want_ptrs.refreshTokenRaw, mm_got.refreshTokenRaw, minimock.Diff(*mm_want_ptrs.refreshTokenRaw, mm_got.refreshTokenRaw))
			}

			if mm_want_ptrs.accessTokenRaw != nil && !minimock.Equal(*mm_want_ptrs.accessTokenRaw, mm_got.accessTokenRaw) {
				mmRefreshTokens.t.Errorf("AuthServiceMock.RefreshTokens got unexpected parameter accessTokenRaw, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefreshTokens.RefreshTokensMock.defaultExpectation.expectationOrigins.originAccessTokenRaw, *mm_want_ptrs.accessTokenRaw, mm_got.accessTokenRaw, minimock.Diff(*mm_want_ptrs.accessTokenRaw, mm_got.accessTokenRaw))
			}

			if mm_want_ptrs.ip != nil && !minimock.Equal(*mm_want_ptrs.ip, mm_got.ip) {
				mmRefreshTokens.t.Errorf("AuthServiceMock.RefreshTokens got unexpected parameter ip, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefreshTokens.RefreshTokensMock.defaultExpectation.expectationOrigins.originIp, *mm_want_ptrs.ip, mm_got.ip, minimock.Diff(*mm_want_ptrs.ip, mm_got.ip))
			}

			if mm_want_ptrs.userAgent != nil && !minimock.Equal(*mm_want_ptrs.userAgent, mm_got.userAgent) {
				mmRefreshTokens.t.Errorf("AuthServiceMock.RefreshTokens got unexpected parameter userAgent, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefreshTokens.RefreshTokensMock.defaultExpectation.expectationOrigins.originUserAgent, *mm_want_ptrs.userAgent, mm_got.userAgent, minimock.Diff(*mm_want_ptrs.userAgent, mm_got.userAgent))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRefreshTokens.t.Errorf("AuthServiceMock.RefreshTokens got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRefreshTokens.RefreshTokensMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRefreshTokens.RefreshTokensMock.defaultExpectation.results
		if mm_results == nil {
			mmRefreshTokens.t.Fatal("No results are set for the AuthServiceMock.RefreshTokens")
		}
		return (*mm_results).ap1, (*mm_results).err
	}
	if mmRefreshTokens.funcRefreshTokens != nil {
		return mmRefreshTokens.funcRefreshTokens(ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent)
	}
	mmRefreshTokens.t.Fatalf("Unexpected call to AuthServiceMock.RefreshTokens. %v %v %v %v %v", ctx, refreshTokenRaw, accessTokenRaw, ip, userAgent)
	return
}

// RefreshTokensAfterCounter returns a count of finished AuthServiceMock.RefreshTokens invocations
func (mmRefreshTokens *AuthServiceMock) RefreshTokensAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefreshTokens.afterRefreshTokensCounter)
}

// RefreshTokensBeforeCounter returns a count of AuthServiceMock.RefreshTokens invocations
func (mmRefreshTokens *AuthServiceMock) RefreshTokensBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefreshTokens.beforeRefreshTokensCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.RefreshTokens.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRefreshTokens *mAuthServiceMockRefreshTokens) Calls() []*AuthServiceMockRefreshTokensParams {
	mmRefreshTokens.mutex.RLock()

	argCopy := make([]*AuthServiceMockRefreshTokensParams, len(mmRefreshTokens.callArgs))
	copy(argCopy, mmRefreshTokens.callArgs)

	mmRefreshTokens.mutex.RUnlock()

	return argCopy
}

// MinimockRefreshTokensDone returns true if the count of the RefreshTokens invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockRefreshTokensDone() bool {
	if m.RefreshTokensMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RefreshTokensMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RefreshTokensMock.invocationsDone()
}

// MinimockRefreshTokensInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockRefreshTokensInspect() {
	for _, e := range m.RefreshTokensMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.RefreshTokens at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRefreshTokensCounter := mm_atomic.LoadUint64(&m.afterRefreshTokensCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RefreshTokensMock.defaultExpectation != nil && afterRefreshTokensCounter < 1 {
		if m.RefreshTokensMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.RefreshTokens at\n%s", m.RefreshTokensMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.RefreshTokens at\n%s with params: %#v", m.RefreshTokensMock.defaultExpectation.expectationOrigins.origin, *m.RefreshTokensMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRefreshTokens != nil && afterRefreshTokensCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.RefreshTokens at\n%s", m.funcRefreshTokensOrigin)
	}

	if !m.RefreshTokensMock.invocationsDone() && afterRefreshTokensCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.RefreshTokens at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RefreshTokensMock.expectedInvocations), m.RefreshTokensMock.expectedInvocationsOrigin, afterRefreshTokensCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockIssueTokensInspect()

			m.MinimockRefreshTokensInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockIssueTokensDone() &&
		m.MinimockRefreshTokensDone()
}
